{% set name = "pyngo" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyngo-{{ version }}.tar.gz
  sha256: 3ad0db0363de46da989739bc31bc2f04c40282ff26201d5dce6dc90bf2a1bf0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - typing-extensions >=3.7.4,<4.10.0
    - pydantic >=2.5.3
    - django >=3.2.0,<6.0.0

test:
  imports:
    - pyngo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yezz123/pyngo
  summary: Pydantic Package for Adding Models into a Django or Django Rest Framework Project
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
