{% set name = "pyngo" %}
{% set version = "2.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyngo-{{ version }}.tar.gz
  sha256: 4450405fa0b9c9a4fbf56ba24baa696c23ec75f3d4268f86f1aff58e67273ac4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.7.4,<4.13.0
    - pydantic >=2.8.2,<2.11.0
    - django >=3.2.0,<6.0.0

test:
  imports:
    - pyngo
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/yezz123/pyngo
  summary: Pydantic Package for Adding Models into a Django or Django Rest Framework Project
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
